backend:
  name: github
  repo: Validone-LLC/NewEraHockey
  branch: master

# Site URL for preview
site_url: https://newerahockey.validone-llc.com

# Publish mode - set to editorial_workflow for draft/review/publish flow
# Change to 'editorial_workflow' to enable draft → review → publish with previews
publish_mode: simple # Change to: editorial_workflow

# Media storage
media_folder: 'public/assets/images'
public_folder: '/assets/images'

# Collections organized by page sections
collections:
  # ===== CONTENT SECTION =====
  # Home Page Content
  - name: 'content-home-page'
    label: 'Home Page'
    files:
      # Home Hero Section
      - label: 'Hero Section'
        name: 'homeHero'
        file: 'src/data/homeHero.json'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Brand Name', name: 'brandName', widget: 'string' }
          - { label: 'Tagline', name: 'tagline', widget: 'text' }
          - label: 'Primary CTA'
            name: 'primaryCTA'
            widget: 'object'
            fields:
              - { label: 'Button Text', name: 'text', widget: 'string' }
              - { label: 'Link', name: 'link', widget: 'string' }
          - label: 'Secondary CTA'
            name: 'secondaryCTA'
            widget: 'object'
            fields:
              - { label: 'Button Text', name: 'text', widget: 'string' }
              - { label: 'Link', name: 'link', widget: 'string' }
          - { label: 'Logo Image', name: 'logoImage', widget: 'image' }

      # Core Values
      - label: 'Core Values'
        name: 'coreValues'
        file: 'src/data/coreValues.json'
        fields:
          - label: 'Values'
            name: 'coreValues'
            widget: 'list'
            fields:
              - { label: 'ID', name: 'id', widget: 'number', value_type: 'int' }
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Description', name: 'description', widget: 'text' }
              - label: 'Icon'
                name: 'icon'
                widget: 'select'
                options: ['Flame', 'Dumbbell', 'Trophy']
              - {
                  label: 'Gradient Classes',
                  name: 'gradient',
                  widget: 'string',
                  hint: "Tailwind gradient classes, e.g., 'from-teal-400 to-teal-600'",
                }
              - {
                  label: 'Image',
                  name: 'image',
                  widget: 'image',
                  required: false,
                  hint: 'Background image for the value card',
                }

      # Home About Section
      - label: 'About Section'
        name: 'homeAbout'
        file: 'src/data/homeAbout.json'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - label: 'Paragraphs'
            name: 'paragraphs'
            widget: 'list'
            field: { label: 'Paragraph', name: 'paragraph', widget: 'text' }
          - label: 'CTA Button'
            name: 'cta'
            widget: 'object'
            fields:
              - { label: 'Button Text', name: 'text', widget: 'string' }
              - { label: 'Link', name: 'link', widget: 'string' }
          - label: 'Coach Experience Card'
            name: 'experience'
            widget: 'object'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Description', name: 'description', widget: 'text' }
              - label: 'Certifications'
                name: 'certifications'
                widget: 'list'
                field: { label: 'Certification', name: 'cert', widget: 'string' }
          - {
              label: 'Additional Context',
              name: 'additionalContext',
              widget: 'text',
              required: false,
            }

      # Home Stats Section
      - label: 'Stats Section'
        name: 'homeStats'
        file: 'src/data/homeStats.json'
        fields:
          - label: 'Statistics'
            name: 'stats'
            widget: 'list'
            fields:
              - { label: 'ID', name: 'id', widget: 'number', value_type: 'int' }
              - { label: 'Number/Value', name: 'number', widget: 'string' }
              - { label: 'Label', name: 'label', widget: 'string' }
              - {
                  label: 'Gradient Classes',
                  name: 'gradient',
                  widget: 'string',
                  hint: "Tailwind gradient classes, e.g., 'from-teal-400 to-teal-600'",
                }

  # Camp Photos (Home Page Carousel)
  - name: 'content-camp-photos'
    label: 'Camp Photos'
    label_singular: 'Camp Photo'
    folder: 'src/data/camp-photos'
    create: true
    slug: '{{slug}}'
    extension: 'json'
    format: 'json'
    fields:
      - { label: 'ID', name: 'id', widget: 'number', value_type: 'int' }
      - {
          label: 'Photo',
          name: 'src',
          widget: 'image',
          hint: 'Upload or select an image from the media library',
        }
      - { label: 'Caption', name: 'caption', widget: 'string', required: false }
      - {
          label: 'Order',
          name: 'order',
          widget: 'number',
          value_type: 'int',
          hint: 'Display order in carousel',
        }

  # Coach Will Page Content
  - name: 'content-coach-will-page'
    label: 'Coach Will Page'
    files:
      # Coach Will Page Labels
      - label: 'Page Labels & Headings'
        name: 'coachWillPage'
        file: 'src/data/coachWillPage.json'
        fields:
          - label: 'Hero Section'
            name: 'hero'
            widget: 'object'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Tagline', name: 'tagline', widget: 'text' }
          - { label: 'Bio Heading', name: 'bioHeading', widget: 'string' }
          - { label: 'Certifications Heading', name: 'certificationsHeading', widget: 'string' }
          - { label: 'Statement Heading', name: 'statementHeading', widget: 'string' }
          - label: 'CTA Section'
            name: 'cta'
            widget: 'object'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Button Text', name: 'buttonText', widget: 'string' }
              - { label: 'Button Link', name: 'buttonLink', widget: 'string' }

      # Coach Information (Bio, Certifications, etc.)
      - label: 'Coach Information'
        name: 'coachInfo'
        file: 'src/data/coachInfo.js'
        fields:
          - { label: 'Name', name: 'name', widget: 'string' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Image Path', name: 'image', widget: 'image' }
          - { label: 'Vision Statement', name: 'statement', widget: 'text' }
          - label: 'Certifications'
            name: 'certifications'
            widget: 'list'
            fields:
              - { label: 'ID', name: 'id', widget: 'number', value_type: 'int' }
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Organization', name: 'organization', widget: 'string' }

  # Testimonials Page Content
  - name: 'content-testimonials-page'
    label: 'Testimonials Page'
    files:
      # Testimonials Page Labels
      - label: 'Page Labels & Headings'
        name: 'testimonialsPage'
        file: 'src/data/testimonialsPage.json'
        fields:
          - label: 'Hero Section'
            name: 'hero'
            widget: 'object'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Tagline', name: 'tagline', widget: 'text' }
          - { label: 'Featured Stories Title', name: 'featuredTitle', widget: 'string' }
          - { label: 'More Stories Title', name: 'moreStoriesTitle', widget: 'string' }
          - label: 'CTA Section'
            name: 'cta'
            widget: 'object'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Description', name: 'description', widget: 'string' }
              - { label: 'Button Text', name: 'buttonText', widget: 'string' }
              - { label: 'Button Link', name: 'buttonLink', widget: 'string' }

  # Individual Testimonials
  - name: 'content-testimonials'
    label: 'Testimonials'
    label_singular: 'Testimonial'
    folder: 'src/data/testimonials'
    create: true
    slug: '{{year}}-{{month}}-{{slug}}'
    extension: 'json'
    format: 'json'
    fields:
      - { label: 'ID', name: 'id', widget: 'number', value_type: 'int' }
      - { label: 'Author Name', name: 'author', widget: 'string' }
      - {
          label: 'Role/Relation',
          name: 'role',
          widget: 'string',
          hint: "e.g., 'Parent of player' or 'Player'",
        }
      - { label: 'Testimonial Text', name: 'text', widget: 'text' }
      - { label: 'Image', name: 'image', widget: 'image', required: false }
      - { label: 'Featured', name: 'featured', widget: 'boolean', default: false }

  # Gallery Page Content
  - name: 'content-gallery-page'
    label: 'Gallery Page'
    files:
      # Gallery Page Labels
      - label: 'Page Labels & Headings'
        name: 'galleryPage'
        file: 'src/data/galleryPage.json'
        fields:
          - label: 'Hero Section'
            name: 'hero'
            widget: 'object'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Tagline', name: 'tagline', widget: 'text' }
          - { label: 'Images Heading', name: 'imagesHeading', widget: 'string' }
          - label: 'Videos Section'
            name: 'videosSection'
            widget: 'object'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Coming Soon Text', name: 'comingSoon', widget: 'string' }
              - { label: 'Description', name: 'description', widget: 'string' }

      # Gallery Categories
      - label: 'Gallery Categories'
        name: 'galleryCategories'
        file: 'src/data/galleryImages.js'
        fields:
          - label: 'Categories'
            name: 'galleryCategories'
            widget: 'list'
            fields:
              - { label: 'ID', name: 'id', widget: 'number', value_type: 'int' }
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Description', name: 'description', widget: 'string' }

  # Individual Gallery Images
  - name: 'content-gallery-images'
    label: 'Gallery Images'
    label_singular: 'Gallery Image'
    folder: 'src/data/gallery'
    create: true
    slug: '{{slug}}'
    extension: 'json'
    format: 'json'
    fields:
      - { label: 'ID', name: 'id', widget: 'number', value_type: 'int' }
      - {
          label: 'Image',
          name: 'src',
          widget: 'image',
          hint: 'Upload or select an image from the media library',
        }
      - { label: 'Description/Alt Text', name: 'alt', widget: 'string' }
      - label: 'Category'
        name: 'category'
        widget: 'select'
        options: ['players', 'camps', 'behind-scenes']
      - { label: 'Featured', name: 'featured', widget: 'boolean', default: false }

  # Contact Page Content
  - name: 'content-contact-page'
    label: 'Contact Page'
    files:
      # Contact Page Content
      - label: 'Page Content'
        name: 'contactPage'
        file: 'src/data/contactPage.json'
        fields:
          - label: 'Hero Section'
            name: 'hero'
            widget: 'object'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Tagline', name: 'tagline', widget: 'text' }
          - label: 'Contact Info'
            name: 'contactInfo'
            widget: 'object'
            fields:
              - { label: 'Heading', name: 'heading', widget: 'string' }
              - label: 'Email'
                name: 'email'
                widget: 'object'
                fields:
                  - { label: 'Label', name: 'label', widget: 'string' }
                  - { label: 'Email Address', name: 'address', widget: 'string' }
                  - { label: 'Mailto Link', name: 'href', widget: 'string' }
              - label: 'Phone'
                name: 'phone'
                widget: 'object'
                fields:
                  - { label: 'Label', name: 'label', widget: 'string' }
                  - { label: 'Phone Number', name: 'number', widget: 'string' }
                  - { label: 'Tel Link', name: 'href', widget: 'string' }
              - label: 'Instagram'
                name: 'instagram'
                widget: 'object'
                fields:
                  - { label: 'Label', name: 'label', widget: 'string' }
                  - { label: 'Instagram Handle', name: 'handle', widget: 'string' }
                  - { label: 'Instagram URL', name: 'url', widget: 'string' }
          - label: 'Form Section'
            name: 'formSection'
            widget: 'object'
            fields:
              - { label: 'Heading', name: 'heading', widget: 'string' }
          - label: 'FAQ CTA Section'
            name: 'faqCTA'
            widget: 'object'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Description', name: 'description', widget: 'text' }
              - { label: 'Button Text', name: 'buttonText', widget: 'string' }
              - { label: 'Button Link', name: 'buttonLink', widget: 'string' }

      # FAQs
      - label: 'Frequently Asked Questions'
        name: 'faqs'
        file: 'src/data/faqs.json'
        fields:
          - label: 'FAQs'
            name: 'faqs'
            widget: 'list'
            fields:
              - { label: 'ID', name: 'id', widget: 'number', value_type: 'int' }
              - { label: 'Question', name: 'question', widget: 'string' }
              - { label: 'Answer', name: 'answer', widget: 'text' }
  
  - divider: true 
  
  # ===== LEGAL PAGES =====
  - name: 'legal'
    label: 'Legal Pages'
    files:
      # Privacy Policy
      - label: 'Privacy Policy'
        name: 'privacyPolicy'
        file: 'src/data/privacyPolicy.json'
        fields:
          - { label: 'Last Updated', name: 'lastUpdated', widget: 'string' }
          - label: 'Sections'
            name: 'sections'
            widget: 'list'
            fields:
              - { label: 'Section ID', name: 'id', widget: 'string' }
              - { label: 'Title', name: 'title', widget: 'string' }
              - label: 'Content Paragraphs'
                name: 'content'
                widget: 'list'
                field: { label: 'Paragraph', name: 'paragraph', widget: 'text' }

      # Terms and Conditions
      - label: 'Terms & Conditions'
        name: 'termsAndConditions'
        file: 'src/data/termsAndConditions.json'
        fields:
          - { label: 'Last Updated', name: 'lastUpdated', widget: 'string' }
          - label: 'Sections'
            name: 'sections'
            widget: 'list'
            fields:
              - { label: 'Section ID', name: 'id', widget: 'string' }
              - { label: 'Title', name: 'title', widget: 'string' }
              - label: 'Content Paragraphs'
                name: 'content'
                widget: 'list'
                field: { label: 'Paragraph', name: 'paragraph', widget: 'text' }

  # ===== FUTURE FEATURES (PLACEHOLDERS) =====
  # Email Configuration (Not Implemented Yet)
  - divider: true 
  - name: 'email-settings'
    label: 'Email (Not Implemented)'
    files:
      - label: 'Email Configuration'
        name: 'emailConfig'
        file: 'src/data/emailConfig.json'
        fields:
          - { label: 'From Email', name: 'fromEmail', widget: 'string' }
          - { label: 'To Email', name: 'toEmail', widget: 'string' }
          - { label: 'Subject Template', name: 'subjectTemplate', widget: 'string' }

  # Event Calendar (Not Implemented Yet)
  - divider: true 
  - name: 'events'
    label: 'Events (Not Implemented)'
    label_singular: 'Event'
    folder: 'src/data/events'
    create: true
    slug: '{{year}}-{{month}}-{{slug}}'
    extension: 'json'
    format: 'json'
    fields:
      - { label: 'Event Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Start Date', name: 'startDate', widget: 'datetime' }
      - { label: 'End Date', name: 'endDate', widget: 'datetime' }
      - { label: 'Location', name: 'location', widget: 'string' }
      - { label: 'Registration Link', name: 'registrationLink', widget: 'string', required: false }

  # Contact Form Submissions (Not Implemented Yet)
  # Note: This would require backend integration for form submission storage
  - divider: true 
  - name: 'contact-submissions'
    label: 'Contact Submissions (Not Implemented)'
    label_singular: 'Submission'
    folder: 'src/data/contact-submissions'
    create: false
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    extension: 'json'
    format: 'json'
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Email', name: 'email', widget: 'string' }
      - { label: 'Phone', name: 'phone', widget: 'string', required: false }
      - { label: 'Message', name: 'message', widget: 'text' }
      - { label: 'Submitted At', name: 'submittedAt', widget: 'datetime' }
